django/mysite/api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('task/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('register/', views.create_user_form, name='create_user'),
    path('accounts/profile/', views.ProfileView.as_view(), name='profile'),
    path('create_task/', views.create_task, name='create_task'),
    path('change_task/<int:pk>', views.change_task, name='change_task'),
    path('delete_task/<int:pk>', views.delete_task, name='delete_task'),
]

django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('api.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

django/mysite/api/models.py
from django.db import models
from django.contrib.auth import models as a_models

class Task(models.Model):
    creator = models.ForeignKey(a_models.User, on_delete=models.CASCADE, related_name='creator')
    users = models.ManyToManyField(a_models.User)
    name = models.CharField(max_length=200)
    details = models.CharField(max_length=1000)
    end_date = models.DateTimeField()
    
    def __str__(self):
        return self.name

django/mysite/api/forms.py
from django import forms
from django.contrib.auth.models import User


from .models import Task

class DateInput(forms.DateInput):
    input_type = "date"

    def __init__(self, **kwargs):
        kwargs["format"] = "%Y-%m-%d"
        super().__init__(**kwargs)


class TimeInput(forms.TimeInput):
    input_type = "time"


class DateTimeInput(forms.DateTimeInput):
    input_type = "datetime-local"

    def __init__(self, **kwargs):
        kwargs["format"] = "%Y-%m-%dT%H:%M"
        super().__init__(**kwargs)


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ['creator']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["end_date"].widget = DateTimeInput()

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email', 'first_name', 'last_name']

django/mysite/api/views.py
import os
import json

from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.db import IntegrityError
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.forms.models import model_to_dict

from .models import Task
from .forms import TaskForm
from .forms import UserForm


class IndexView(generic.ListView):
    template_name = 'index.html'
    paginate_by = 10
    def get_queryset(self):
        return Task.objects.order_by('-end_date')
    

class ProfileView(generic.ListView):
    template_name = 'profile.html'
    paginate_by = 10
    def get_queryset(self):
        req = self.request
        usr = req.user
        return Task.objects.filter(Q(users=self.request.user) | Q(creator=self.request.user)).distinct().order_by('-end_date')

class DetailView(generic.DetailView):
    model = Task
    template_name = 'detail.html'

def create_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            users = form.cleaned_data.pop('users')
            form.cleaned_data['creator'] = request.user
            task = Task(**form.cleaned_data)
            task.save()
            task.users.set(users)
            task.save()
            return HttpResponseRedirect(reverse('api:detail', args=(task.id,)))
    else:
        form = TaskForm()

    return render(request, 'create_task_form.html', {'form': form})

def change_task(request, pk):
    task = get_object_or_404(Task, id=pk)
    if request.user != task.creator:
        return HttpResponseRedirect('/')
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            users = form.cleaned_data.pop('users')
            task.update(**form)
            task.users.set(users)
            task.save()
            return HttpResponseRedirect(reverse('api:details', args=(task.id,)))
        else:
            task_dict = model_to_dict(task)
            task_dict.pop('id')
            form = TaskForm()
            return render(request, 'change_task_form.html', {'form': form, 'task': task_dict, 'error_message': 'Form was invalid'})
    else:
        form = TaskForm()
    task_dict = model_to_dict(task)
    task_dict.pop('id')
    return render(request, 'change_task_form.html', {'form': form, 'task': task_dict})

def delete_task(request, pk):
    task = get_object_or_404(Task, id=pk)
    if request.user != task.creator:
        return HttpResponseRedirect('/')
    task.delete()
    return HttpResponseRedirect('/accounts/profile')

def create_user_form(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            try:
                user = User.objects.create_user(**form.cleaned_data)
                login(request, user)
            except IntegrityError:
                return render(request, 'create_user_form.html', {
                'error_message': "The user already exists.",
                'form': form
               })
            return HttpResponseRedirect('/accounts/profile/')
    else:
        form = UserForm()

    return render(request, 'create_user_form.html', {'form': form})

django/mysite/templates/change_task_form.html
{% if error_message %}
<p>{{error_message}}</p>
{% endif %}

<form method="post" action="{% url 'api:create_task' %}">
{% csrf_token %}
<table>
{%for field in form %}
<tr>
<td>
{{field.label_tag}}
</td>
<td>
{{field}}
</td>
</tr>
{% endfor %}
</table>
<input type="submit" value="Change Task">
</form>

<p>The task used to be: </p>
<table>
{%for key, value in task.items %}
<tr>
<td>
{{key.capitalize}}
</td>
<td>
{% if key != "users" %}
{{value}}
{% else %}
<ul>
{% for usr in value %}
<li>{{usr.username}}</li>
{%endfor%}
</ul>
{% endif %}
</td>
</tr>
{% endfor %}
</table>

django/mysite/templates/create_task_form.html
<form method="post" action="{% url 'api:create_task' %}">
{% csrf_token %}
<table>
{%for field in form %}
<tr>
<td>
{{field.label_tag}}
</td>
<td>
{{field}}
</td>
</tr>
{% endfor %}
</table>
<input type="submit" value="Create Task">
</form>

django/mysite/templates/create_user_form.html
<form action="{% url 'api:create_user' %}" method="post">
{% csrf_token %}
<h1>Register</h1>
{% if error_message %}
<p>{{error_message}}</p>
{% endif %}
<table>
{%for field in form %}
<tr>
<td>
{{field.label_tag}}
</td>
<td>
{% if field.name == 'password' %}
    <input type="password" name="password">
{%else%}
    {{field}}
{%endif%}
</td>
</tr>
{% endfor %}
</table>

<input type="submit" value="Register">
</form>

<p><a href="/accounts/login/">Log In</a></p>

django/mysite/templates/detail.html
<h1>{{task.name}}</h1>
<h3>{{task.details}}</h3>
<p>Responsible users</p>
<ul>
{% for t_user in task.users.all %}
<li>{{ t_user.username }}</li>
{% endfor %}
</ul>
<p>{{ task.end_date }}</p>
<p><a href="/">Task list</a></p>

django/mysite/templates/index.html
{% if user.is_anonymous %}
<p><a href="/accounts/login">Log In</a></p>
<p><a href="/register/">Register</a></p>
{% else %}
<p><a href="{% url 'api:profile' %}">Profile</a></p>
<p><a href="/accounts/logout">Log Out</a></p>
<p><a href="{% url 'api:create_task' %}">Create a task</a>
{% endif %}

{% if page_obj %}

    {% if page_obj.has_previous %}
        <p><a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a><p>
    {% endif %}
    {% if page_obj.has_next %}
        <p><a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a><p>
    {% endif %}

    <ul>
    {% for task in page_obj%}
        <li><a href="{% url 'api:detail' task.id %}">{{ task.name }}</a></li>
    {% endfor %}
    </ul>
    
{% else %}
    <p>No tasks are available.</p>
{% endif %}

django/mysite/templates/profile.html
<h1>{{ user.username }}</h1>

{% if page_obj %}
    {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
{% for task in page_obj%}
    <h2>
        <a href="{% url 'api:detail' task.id %}">{{task.name}}</a> 
        {% if task.creator.username == user.username %}
        <a href="{% url 'api:change_task' task.id %}"> Edit</a> 
        <a href="{% url 'api:delete_task' task.id %}"> Delete</a>
        {% endif %}
    </h2>
<p>{{ task.details }}</p>
{% endfor %}

{% endif %}
<p><a href="/">Task list</a></p>

django/mysite/templates/results.html
<h1>{{ survey.name}}</h1>

{% for question in survey.question_set.all %}

<h3>{{question.question_text}}</h3>

{% if question.multiple_choice %}
    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>
{% else %}
    <ul>
    {% for answer in question.questionanswers_set.all %}
        <li>{{ answer.answer }}</li>
    {% endfor %}
    </ul>
{% endif %}


{% endfor %}
<p><a href="{% url 'api:detail' survey.id %}">Vote again?</a></p>
<p><a href="/">Surveys list</a></p>